import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface GeneratePDFProps {
  imageUrl: string;
  prediction: string;
  confidence: number;
}

export const generatePDF = async ({
  imageUrl,
  prediction,
  confidence
}: GeneratePDFProps): Promise<void> => {
  const doc = new jsPDF();

  // Add title
  doc.setFontSize(22);
  doc.setTextColor(33, 33, 33);
  doc.text("Rice Variety Classification Report", 15, 20);
  
  // Add subtitle
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text("Powered by Rice-Classifier AI", 15, 30);
  
  // Add horizontal line
  doc.setDrawColor(200, 200, 200);
  doc.line(15, 35, 195, 35);
  
  // Add timestamp
  const now = new Date();
  doc.setFontSize(10);
  doc.text(`Generated on: ${now.toLocaleString()}`, 15, 42);

  // Add image
  try {
    // Load image
    const img = new Image();
    img.crossOrigin = "Anonymous";  // Handle CORS issues
    
    await new Promise<void>((resolve, reject) => {
      img.onload = () => {
        try {
          // Calculate aspect ratio to fit within 80x80
          const maxWidth = 80;
          const maxHeight = 80;
          let width = img.width;
          let height = img.height;
          
          if (width > height) {
            if (width > maxWidth) {
              height = height * (maxWidth / width);
              width = maxWidth;
            }
          } else {
            if (height > maxHeight) {
              width = width * (maxHeight / height);
              height = maxHeight;
            }
          }
          
          doc.text("Input Image:", 15, 55);
          doc.addImage(img, 'JPEG', 15, 60, width, height);
          resolve();
        } catch (error) {
          console.error("Error adding image to PDF:", error);
          // Add placeholder text if image fails
          doc.text("(Image could not be rendered)", 15, 65);
          resolve();
        }
      };
      
      img.onerror = () => {
        console.error("Error loading image for PDF");
        // Add placeholder text if image fails to load
        doc.text("(Image could not be loaded)", 15, 65);
        resolve();
      };
      
      img.src = imageUrl;
    });
  } catch (error) {
    console.error("Error in image processing:", error);
    doc.text("(Image processing error)", 15, 65);
  }

  // Add results section
  doc.setFontSize(16);
  doc.setTextColor(33, 33, 33);
  doc.text("Classification Results", 105, 60);
  
  // Add classification results table
  autoTable(doc, {
    startY: 65,
    margin: { left: 105 },
    head: [['Parameter', 'Value']],
    body: [
      ['Rice Variety', prediction],
      ['Confidence', `${(confidence * 100).toFixed(2)}%`],
      ['Analysis Method', 'Convolutional Neural Network'],
      ['Model Version', 'RiceNet v2.1']
    ],
    theme: 'grid',
    headStyles: { fillColor: [74, 222, 128], textColor: [0, 0, 0] },
    alternateRowStyles: { fillColor: [240, 240, 240] }
  });
  
  // Add rice variety information
  doc.setFontSize(16);
  doc.setTextColor(33, 33, 33);
  doc.text("Rice Variety Information", 15, 150);
  
  let varietyInfo = "";
  switch (prediction) {
    case "Arborio":
      varietyInfo = "Arborio rice is a short-grain rice named after the town of Arborio in the Po Valley of Italy. It's high in amylopectin starch, which gives risotto its creamy texture.";
      break;
    case "Basmati":
      varietyInfo = "Basmati is a long-grain rice known for its fragrance and delicate flavor. It's primarily grown in India and Pakistan, and is a staple in many South Asian cuisines.";
      break;
    case "Ipsala":
      varietyInfo = "Ipsala rice is grown in the Ipsala district of Turkey. It's known for its medium grain size and is commonly used in Turkish and Mediterranean dishes.";
      break;
    case "Jasmine":
      varietyInfo = "Jasmine rice is a long-grain variety known for its floral aroma. It's primarily grown in Thailand and is slightly sticky when cooked.";
      break;
    case "Karacadag":
      varietyInfo = "Karacadag rice is a traditional variety grown near the Karacadag mountain in Turkey. It has a distinctive taste and is used in special regional dishes.";
      break;
    default:
      varietyInfo = "Information about this rice variety is not available.";
  }
  
  doc.setFontSize(12);
  doc.setTextColor(60, 60, 60);
  
  // Add wrapped text for variety information
  const splitText = doc.splitTextToSize(varietyInfo, 180);
  doc.text(splitText, 15, 160);
  
  // Add footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Report generated by Rice-Classifier AI", 15, 285);
  doc.text("Page 1 of 1", 180, 285);
  
  // Save the PDF
  doc.save("Rice_Variety_Classification_Report.pdf");
};